# Generated by Django 5.1.5 on 2025-02-01 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycrud', '0003_employees_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='image',
        ),
    ]
