# Generated by Django 5.1.5 on 2025-02-01 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycrud', '0004_remove_employees_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employees',
            new_name='students',
        ),
    ]
